//Some questions for testing

const questions = [
  {
    id: '1',
    dif: 1,
    language: 'spanish',
    question: 'How do you say "hello" in Spanish?',
    options: ['Hola', 'Bonjour', 'Namaste', 'Ciao'],
    correctAnswer: 'Hola',
  },
  {
    id: '2',
    dif: 3,
    language: 'french',
    question: 'How do you say "thank you" in French?',
    options: ['Merci', 'Grazie', 'Dhanyavaad', 'Gracias'],
    correctAnswer: 'Merci',
  },
  {
    id: '3',
    dif: 3,
    language: 'hindi',
    question: 'What is the Hindi word for "water"?',
    options: ['Eau', 'Pani', 'Aqua', 'Agua'],
    correctAnswer: 'Pani',
  },
  {
    id: '4',
    dif: 3,
    language: 'spanish',
    question: 'How do you say "goodbye" in Spanish?',
    options: ['Au revoir', 'Adiós', 'Alvidaa', 'Arrivederci'],
    correctAnswer: 'Adiós',
  },
  {
    id: '5',
    dif: 1,
    language: 'italian',
    question: 'What is the Italian word for "pizza"?',
    options: ['Pizza', 'Pasta', 'Risotto', 'Spaghetti'],
    correctAnswer: 'Pizza',
  },
  {
    id: '6',
    dif: 1,
    language: 'portuguese',
    question: 'How do you say "apple" in Portuguese?',
    options: ['Maçã', 'Maçã-verde', 'Fruta', 'Pera'],
    correctAnswer: 'Maçã',
  },
  {
    id: '7',
    dif: 3,
    language: 'spanish',
    question: 'What is the English word for "libro"?',
    options: ['Book', 'Table', 'Chair', 'Pen'],
    correctAnswer: 'Book',
  },
  {
    id: '8',
    dif: 3,
    language: 'hindi',
    question: 'How do you say "good morning" in Hindi?',
    options: ['Buenos días', 'Namaste', 'Bonjour', 'Buongiorno'],
    correctAnswer: 'Namaste',
  },
  {
    id: '9',
    dif: 3,
    language: 'italian',
    question: 'What is the French word for "sun"?',
    options: ['Soleil', 'Lune', 'Étoile', 'Pluie'],
    correctAnswer: 'Soleil',
  },
  {
    id: '10',
    dif: 5,
    language: 'spanish',
    question: 'How do you say "bread" in Spanish?',
    options: ['Pan', 'Queso', 'Fruta', 'Verdura'],
    correctAnswer: 'Pan',
  },
// Existing questions...

{
  id: '11',
  dif: 2,
  language: 'english',
  question: 'What is the capital of France?',
  options: ['London', 'Berlin', 'Madrid', 'Paris'],
  correctAnswer: 'Paris',
},
{
  id: '12',
  dif: 2,
  language: 'spanish',
  question: 'How do you say "cat" in Spanish?',
  options: ['Perro', 'Gato', 'Conejo', 'Pájaro'],
  correctAnswer: 'Gato',
},
{
  id: '13',
  dif: 4,
  language: 'french',
  question: 'What is the French word for "tree"?',
  options: ['Fleur', 'Arbre', 'Montagne', 'Maison'],
  correctAnswer: 'Arbre',
},
{
  id: '14',
  dif: 4,
  language: 'hindi',
  question: 'What is the Hindi word for "sky"?',
  options: ['Aasman', 'Pani', 'Dharti', 'Hawa'],
  correctAnswer: 'Aasman',
},
{
  id: '15',
  dif: 1,
  language: 'italian',
  question: 'How do you say "car" in Italian?',
  options: ['Auto', 'Bicicletta', 'Treno', 'Macchina'],
  correctAnswer: 'Macchina',
},
{
  id: '16',
  dif: 1,
  language: 'portuguese',
  question: 'What is the Portuguese word for "beach"?',
  options: ['Praia', 'Montanha', 'Rio', 'Cidade'],
  correctAnswer: 'Praia',
},
{
  id: '17',
  dif: 3,
  language: 'english',
  question: 'How do you say "sun" in Spanish?',
  options: ['Sol', 'Luna', 'Estrella', 'Nube'],
  correctAnswer: 'Sol',
},
{
  id: '18',
  dif: 3,
  language: 'hindi',
  question: 'What is the English word for "दिन" (day) in Hindi?',
  options: ['Day', 'Night', 'Sun', 'Moon'],
  correctAnswer: 'Day',
},
{
  id: '19',
  dif: 3,
  language: 'italian',
  question: 'What is the Spanish word for "mountain"?',
  options: ['Montaña', 'Playa', 'Río', 'Ciudad'],
  correctAnswer: 'Montaña',
},
{
  id: '20',
  dif: 5,
  language: 'spanish',
  question: 'How do you say "butterfly" in Spanish?',
  options: ['Mariposa', 'Abeja', 'Hormiga', 'Mosca'],
  correctAnswer: 'Mariposa',
},


{
  id: '21',
  dif: 2,
  language: 'english',
  question: 'What is the plural form of "book" in English?',
  options: ['Books', 'Bookies', 'Bookses', 'Book'],
  correctAnswer: 'Books',
},
{
  id: '22',
  dif: 2,
  language: 'english',
  question: 'Which word means the opposite of "happy" in English?',
  options: ['Sad', 'Angry', 'Excited', 'Joyful'],
  correctAnswer: 'Sad',
},
{
  id: '23',
  dif: 4,
  language: 'english',
  question: 'What is the English word for "école"?',
  options: ['School', 'Hospital', 'Market', 'Library'],
  correctAnswer: 'School',
},
{
  id: '24',
  dif: 4,
  language: 'english',
  question: 'What is the English word for "table"?',
  options: ['Table', 'Chair', 'Desk', 'Couch'],
  correctAnswer: 'Table',
},
{
  id: '25',
  dif: 1,
  language: 'english',
  question: 'What is the opposite of "big" in English?',
  options: ['Small', 'Large', 'Huge', 'Giant'],
  correctAnswer: 'Small',
},
{
  id: '26',
  dif: 1,
  language: 'english',
  question: 'How do you say "hello" in English?',
  options: ['Hi', 'Hola', 'Bonjour', 'Ciao'],
  correctAnswer: 'Hi',
},
{
  id: '27',
  dif: 3,
  language: 'english',
  question: 'What is the English word for "zoo"?',
  options: ['Zoo', 'Museum', 'Park', 'Cinema'],
  correctAnswer: 'Zoo',
},
{
  id: '28',
  dif: 3,
  language: 'english',
  question: 'How do you say "apple" in English?',
  options: ['Apple', 'Banana', 'Orange', 'Grapes'],
  correctAnswer: 'Apple',
},
{
  id: '29',
  dif: 3,
  language: 'english',
  question: 'What is the plural form of "child" in English?',
  options: ['Children', 'Childs', 'Childes', 'Child'],
  correctAnswer: 'Children',
},
{
  id: '30',
  dif: 5,
  language: 'english',
  question: 'How do you say "goodbye" in English?',
  options: ['Goodbye', 'Hello', 'Hi', 'Bye'],
  correctAnswer: 'Goodbye',
},

// Add more questions here...

];



export default questions;
