const questions = [
  {
    id:'1',
    dif:1,
    language: 'spanish',
    question: 'How do you say "hello" in Spanish?',
    options: ['Hola', 'Bonjour', 'Namaste', 'Ciao'],
    correctAnswer: 'Hola',
  },
  {
    id:'2',
    dif:3,
    language: 'french',
    question: 'How do you say "thank you" in French?',
    options: ['Merci', 'Grazie', 'Dhanyavaad', 'Gracias'],
    correctAnswer: 'Merci',
  },
  {
    id:'10',
    dif:3,
    language: 'hindi',
    question: 'What is the Hindi word for "water"?',
    options: ['Eau', 'Pani', 'Aqua', 'Agua'],
    correctAnswer: 'Pani',
  },
  {
    id:'3',
    dif:3,
    language: 'spanish',
    question: 'How do you say "goodbye" in Spanish?',
    options: ['Au revoir', 'Adiós', 'Alvidaa', 'Arrivederci'],
    correctAnswer: 'Adiós',
  },
  {
    id:'4',
    dif:1,
    language: 'italian',
    question: 'What is the Italian word for "pizza"?',
    options: ['Pizza', 'Pasta', 'Risotto', 'Spaghetti'],
    correctAnswer: 'Pizza',
  },
  {
    id:'5',
    dif:1,
    language: 'portuguese',
    question: 'How do you say "apple" in Portuguese?',
    options: ['Maçã', 'Maçã-verde', 'Fruta', 'Pera'],
    correctAnswer: 'Maçã',
  },
  {
    id:'6',
    dif:3,
    language: 'spanish',
    question: 'What is the English word for "libro"?',
    options: ['Book', 'Table', 'Chair', 'Pen'],
    correctAnswer: 'Book',
  },
  {
    id:'7',
    dif:3,
    language: 'hindi',
    question: 'How do you say "good morning" in Hindi?',
    options: ['Buenos días', 'Namaste', 'Bonjour', 'Buongiorno'],
    correctAnswer: 'Namaste',
  },
  {
    id:'8',
    dif:3,
    language: 'italian',
    question: 'What is the French word for "sun"?',
    options: ['Soleil', 'Lune', 'Étoile', 'Pluie'],
    correctAnswer: 'Soleil',
  },
  {
    id:'9',
    dif:5,
    language: 'spanish',
    question: 'How do you say "bread" in Spanish?',
    options: ['Pan', 'Queso', 'Fruta', 'Verdura'],
    correctAnswer: 'Pan',
  },
];

export default questions;
